from collections import namedtuple

canopies = namedtuple('canopies', ['sea', 
                                   'glacier',
                                   'in_lake',
                                   'ever_nl',
                                   'ever_bl',
                                   'deci_nl',
                                   'deci_bl',
                                   'trop_bl',
                                   'dry_tr',
                                   'ever_sh',
                                   'deci_sh',
                                   'thor_sh',
                                   'shor_gr',
                                   'long_gr',
                                   'crops',
                                   'rice',
                                   'sugar',
                                   'maize',
                                   'cotton',
                                   'irr_cr',
                                   'urban',
                                   'tundra',
                                   'swamp',
                                   'desert',
                                   'mx_tree',
                                   'mx_sh'], defaults=[0]*26)