from collections import namedtuple

landcover_types = ['sea', 
                    'glacier',
                    'in_lake',
                    'ever_nl',
                    'ever_bl',
                    'deci_nl',
                    'deci_bl',
                    'trop_bl',
                    'dry_tr',
                    'ever_sh',
                    'deci_sh',
                    'thor_sh',
                    'shor_gr',
                    'long_gr',
                    'crops',
                    'rice',
                    'sugar',
                    'maize',
                    'cotton',
                    'irr_cr',
                    'urban',
                    'tundra',
                    'swamp',
                    'desert',
                    'mx_tree',
                    'mx_sh']

canopies = namedtuple('canopies', landcover_types, defaults=[0.0]*len(landcover_types))

# defaults from https://mesh-model.atlassian.net/wiki/spaces/USER/pages/6390712/Land+cover+types+in+SVS [2026-06-12]
z0v = namedtuple('z0v', landcover_types, 
                        defaults=[0.001, 
                                    0.001,
                                    0.001,
                                    1.75,
                                    2.0,
                                    1.0,
                                    2.0,
                                    3.0,
                                    0.8,
                                    0.1,
                                    0.2,
                                    0.2,
                                    0.1,
                                    0.1,
                                    0.15,
                                    0.15,
                                    0.35,
                                    0.25,
                                    0.1,
                                    0.25,
                                    5.0,
                                    0.1,
                                    0.1,
                                    0.1,
                                    1.75,
                                    0.5])